language: python
python: 2.7

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=py26-twtrunk
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=py26-twlatest
    - TOX_ENV=py27-twlatest
    - TOX_ENV=pypy-twlatest
    - TOX_ENV=pyflakes

install:
    - ./.travis/install.sh

script: tox -e $TOX_ENV

notifications:
    email: false