language: python
python: 2.7

env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    #- TOX_ENV=pypy
    - TOX_ENV=pyflakes

before_install:
    - sudo add-apt-repository -y ppa:pypy/ppa
    - sudo apt-get -y update
    - sudo apt-get install -y pypy pypy-dev
    - sudo rm -rf /usr/local/pypy/bin
    - pip install tox

script: tox -e $TOX_ENV

notifications:
    email: false
